# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/visual-rock/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(CMAKE_COMMAND) -E cmake_progress_start /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend/CMakeFiles /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend/lib/served/CMakeFiles/progress.marks
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f CMakeFiles/Makefile2 lib/served/all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f CMakeFiles/Makefile2 lib/served/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f CMakeFiles/Makefile2 lib/served/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f CMakeFiles/Makefile2 lib/served/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
lib/served/CMakeFiles/served.dir/rule:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f CMakeFiles/Makefile2 lib/served/CMakeFiles/served.dir/rule
.PHONY : lib/served/CMakeFiles/served.dir/rule

# Convenience name for target.
served: lib/served/CMakeFiles/served.dir/rule

.PHONY : served

# fast build rule for target.
served/fast:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/build
.PHONY : served/fast

methods_handler.o: methods_handler.cpp.o

.PHONY : methods_handler.o

# target to build an object file
methods_handler.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/methods_handler.cpp.o
.PHONY : methods_handler.cpp.o

methods_handler.i: methods_handler.cpp.i

.PHONY : methods_handler.i

# target to preprocess a source file
methods_handler.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/methods_handler.cpp.i
.PHONY : methods_handler.cpp.i

methods_handler.s: methods_handler.cpp.s

.PHONY : methods_handler.s

# target to generate assembly for a file
methods_handler.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/methods_handler.cpp.s
.PHONY : methods_handler.cpp.s

multiplexer.o: multiplexer.cpp.o

.PHONY : multiplexer.o

# target to build an object file
multiplexer.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/multiplexer.cpp.o
.PHONY : multiplexer.cpp.o

multiplexer.i: multiplexer.cpp.i

.PHONY : multiplexer.i

# target to preprocess a source file
multiplexer.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/multiplexer.cpp.i
.PHONY : multiplexer.cpp.i

multiplexer.s: multiplexer.cpp.s

.PHONY : multiplexer.s

# target to generate assembly for a file
multiplexer.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/multiplexer.cpp.s
.PHONY : multiplexer.cpp.s

mux/regex_matcher.o: mux/regex_matcher.cpp.o

.PHONY : mux/regex_matcher.o

# target to build an object file
mux/regex_matcher.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/regex_matcher.cpp.o
.PHONY : mux/regex_matcher.cpp.o

mux/regex_matcher.i: mux/regex_matcher.cpp.i

.PHONY : mux/regex_matcher.i

# target to preprocess a source file
mux/regex_matcher.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/regex_matcher.cpp.i
.PHONY : mux/regex_matcher.cpp.i

mux/regex_matcher.s: mux/regex_matcher.cpp.s

.PHONY : mux/regex_matcher.s

# target to generate assembly for a file
mux/regex_matcher.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/regex_matcher.cpp.s
.PHONY : mux/regex_matcher.cpp.s

mux/static_matcher.o: mux/static_matcher.cpp.o

.PHONY : mux/static_matcher.o

# target to build an object file
mux/static_matcher.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/static_matcher.cpp.o
.PHONY : mux/static_matcher.cpp.o

mux/static_matcher.i: mux/static_matcher.cpp.i

.PHONY : mux/static_matcher.i

# target to preprocess a source file
mux/static_matcher.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/static_matcher.cpp.i
.PHONY : mux/static_matcher.cpp.i

mux/static_matcher.s: mux/static_matcher.cpp.s

.PHONY : mux/static_matcher.s

# target to generate assembly for a file
mux/static_matcher.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/static_matcher.cpp.s
.PHONY : mux/static_matcher.cpp.s

mux/variable_matcher.o: mux/variable_matcher.cpp.o

.PHONY : mux/variable_matcher.o

# target to build an object file
mux/variable_matcher.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/variable_matcher.cpp.o
.PHONY : mux/variable_matcher.cpp.o

mux/variable_matcher.i: mux/variable_matcher.cpp.i

.PHONY : mux/variable_matcher.i

# target to preprocess a source file
mux/variable_matcher.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/variable_matcher.cpp.i
.PHONY : mux/variable_matcher.cpp.i

mux/variable_matcher.s: mux/variable_matcher.cpp.s

.PHONY : mux/variable_matcher.s

# target to generate assembly for a file
mux/variable_matcher.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/mux/variable_matcher.cpp.s
.PHONY : mux/variable_matcher.cpp.s

net/connection.o: net/connection.cpp.o

.PHONY : net/connection.o

# target to build an object file
net/connection.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/connection.cpp.o
.PHONY : net/connection.cpp.o

net/connection.i: net/connection.cpp.i

.PHONY : net/connection.i

# target to preprocess a source file
net/connection.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/connection.cpp.i
.PHONY : net/connection.cpp.i

net/connection.s: net/connection.cpp.s

.PHONY : net/connection.s

# target to generate assembly for a file
net/connection.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/connection.cpp.s
.PHONY : net/connection.cpp.s

net/connection_manager.o: net/connection_manager.cpp.o

.PHONY : net/connection_manager.o

# target to build an object file
net/connection_manager.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/connection_manager.cpp.o
.PHONY : net/connection_manager.cpp.o

net/connection_manager.i: net/connection_manager.cpp.i

.PHONY : net/connection_manager.i

# target to preprocess a source file
net/connection_manager.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/connection_manager.cpp.i
.PHONY : net/connection_manager.cpp.i

net/connection_manager.s: net/connection_manager.cpp.s

.PHONY : net/connection_manager.s

# target to generate assembly for a file
net/connection_manager.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/connection_manager.cpp.s
.PHONY : net/connection_manager.cpp.s

net/server.o: net/server.cpp.o

.PHONY : net/server.o

# target to build an object file
net/server.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/server.cpp.o
.PHONY : net/server.cpp.o

net/server.i: net/server.cpp.i

.PHONY : net/server.i

# target to preprocess a source file
net/server.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/server.cpp.i
.PHONY : net/server.cpp.i

net/server.s: net/server.cpp.s

.PHONY : net/server.s

# target to generate assembly for a file
net/server.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/net/server.cpp.s
.PHONY : net/server.cpp.s

parameters.o: parameters.cpp.o

.PHONY : parameters.o

# target to build an object file
parameters.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/parameters.cpp.o
.PHONY : parameters.cpp.o

parameters.i: parameters.cpp.i

.PHONY : parameters.i

# target to preprocess a source file
parameters.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/parameters.cpp.i
.PHONY : parameters.cpp.i

parameters.s: parameters.cpp.s

.PHONY : parameters.s

# target to generate assembly for a file
parameters.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/parameters.cpp.s
.PHONY : parameters.cpp.s

plugins/access_log.o: plugins/access_log.cpp.o

.PHONY : plugins/access_log.o

# target to build an object file
plugins/access_log.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/plugins/access_log.cpp.o
.PHONY : plugins/access_log.cpp.o

plugins/access_log.i: plugins/access_log.cpp.i

.PHONY : plugins/access_log.i

# target to preprocess a source file
plugins/access_log.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/plugins/access_log.cpp.i
.PHONY : plugins/access_log.cpp.i

plugins/access_log.s: plugins/access_log.cpp.s

.PHONY : plugins/access_log.s

# target to generate assembly for a file
plugins/access_log.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/plugins/access_log.cpp.s
.PHONY : plugins/access_log.cpp.s

request.o: request.cpp.o

.PHONY : request.o

# target to build an object file
request.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request.cpp.o
.PHONY : request.cpp.o

request.i: request.cpp.i

.PHONY : request.i

# target to preprocess a source file
request.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request.cpp.i
.PHONY : request.cpp.i

request.s: request.cpp.s

.PHONY : request.s

# target to generate assembly for a file
request.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request.cpp.s
.PHONY : request.cpp.s

request_parser.o: request_parser.cpp.o

.PHONY : request_parser.o

# target to build an object file
request_parser.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request_parser.cpp.o
.PHONY : request_parser.cpp.o

request_parser.i: request_parser.cpp.i

.PHONY : request_parser.i

# target to preprocess a source file
request_parser.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request_parser.cpp.i
.PHONY : request_parser.cpp.i

request_parser.s: request_parser.cpp.s

.PHONY : request_parser.s

# target to generate assembly for a file
request_parser.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request_parser.cpp.s
.PHONY : request_parser.cpp.s

request_parser_impl.o: request_parser_impl.cpp.o

.PHONY : request_parser_impl.o

# target to build an object file
request_parser_impl.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request_parser_impl.cpp.o
.PHONY : request_parser_impl.cpp.o

request_parser_impl.i: request_parser_impl.cpp.i

.PHONY : request_parser_impl.i

# target to preprocess a source file
request_parser_impl.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request_parser_impl.cpp.i
.PHONY : request_parser_impl.cpp.i

request_parser_impl.s: request_parser_impl.cpp.s

.PHONY : request_parser_impl.s

# target to generate assembly for a file
request_parser_impl.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/request_parser_impl.cpp.s
.PHONY : request_parser_impl.cpp.s

response.o: response.cpp.o

.PHONY : response.o

# target to build an object file
response.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/response.cpp.o
.PHONY : response.cpp.o

response.i: response.cpp.i

.PHONY : response.i

# target to preprocess a source file
response.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/response.cpp.i
.PHONY : response.cpp.i

response.s: response.cpp.s

.PHONY : response.s

# target to generate assembly for a file
response.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/response.cpp.s
.PHONY : response.cpp.s

status.o: status.cpp.o

.PHONY : status.o

# target to build an object file
status.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/status.cpp.o
.PHONY : status.cpp.o

status.i: status.cpp.i

.PHONY : status.i

# target to preprocess a source file
status.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/status.cpp.i
.PHONY : status.cpp.i

status.s: status.cpp.s

.PHONY : status.s

# target to generate assembly for a file
status.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/status.cpp.s
.PHONY : status.cpp.s

uri.o: uri.cpp.o

.PHONY : uri.o

# target to build an object file
uri.cpp.o:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/uri.cpp.o
.PHONY : uri.cpp.o

uri.i: uri.cpp.i

.PHONY : uri.i

# target to preprocess a source file
uri.cpp.i:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/uri.cpp.i
.PHONY : uri.cpp.i

uri.s: uri.cpp.s

.PHONY : uri.s

# target to generate assembly for a file
uri.cpp.s:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(MAKE) -f lib/served/CMakeFiles/served.dir/build.make lib/served/CMakeFiles/served.dir/uri.cpp.s
.PHONY : uri.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... served"
	@echo "... methods_handler.o"
	@echo "... methods_handler.i"
	@echo "... methods_handler.s"
	@echo "... multiplexer.o"
	@echo "... multiplexer.i"
	@echo "... multiplexer.s"
	@echo "... mux/regex_matcher.o"
	@echo "... mux/regex_matcher.i"
	@echo "... mux/regex_matcher.s"
	@echo "... mux/static_matcher.o"
	@echo "... mux/static_matcher.i"
	@echo "... mux/static_matcher.s"
	@echo "... mux/variable_matcher.o"
	@echo "... mux/variable_matcher.i"
	@echo "... mux/variable_matcher.s"
	@echo "... net/connection.o"
	@echo "... net/connection.i"
	@echo "... net/connection.s"
	@echo "... net/connection_manager.o"
	@echo "... net/connection_manager.i"
	@echo "... net/connection_manager.s"
	@echo "... net/server.o"
	@echo "... net/server.i"
	@echo "... net/server.s"
	@echo "... parameters.o"
	@echo "... parameters.i"
	@echo "... parameters.s"
	@echo "... plugins/access_log.o"
	@echo "... plugins/access_log.i"
	@echo "... plugins/access_log.s"
	@echo "... request.o"
	@echo "... request.i"
	@echo "... request.s"
	@echo "... request_parser.o"
	@echo "... request_parser.i"
	@echo "... request_parser.s"
	@echo "... request_parser_impl.o"
	@echo "... request_parser_impl.i"
	@echo "... request_parser_impl.s"
	@echo "... response.o"
	@echo "... response.i"
	@echo "... response.s"
	@echo "... status.o"
	@echo "... status.i"
	@echo "... status.s"
	@echo "... uri.o"
	@echo "... uri.i"
	@echo "... uri.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /media/visual-rock/Extern4tb/Projects/GitRepos/zwoo/backend && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

